server:
  port: 5000

backend-url: "https://api.dreamhub.link"

feign.httpclient.enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC