server:
  port: 5000

backend-url: "https://api.dreamhub.link"

feign.httpclient.enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: BASIC

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 747552759595-acdsv33rtnp61a4lihl9jsse8hsm5pt8.apps.googleusercontent.com
            client-secret: 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