server:
  port: 5000

spring:
  datasource:
    url: "jdbc:mysql://dev-monsterhub-db.cvdxwooziepy.eu-west-3.rds.amazonaws.com:3306/dreamhub?useLegacyDatetimeCode=false&amp&serverTimezone=UTC&characterEncoding=UTF8"
    password: "a!q<=G6)WC%D"
    username: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update